version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17  # PostgreSQL 17 with pgvector pre-installed
    container_name: pgvector-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
